modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "dergstuff"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile="assets/dergstuff/icon.png"
description = '''${mod_description}'''
authors = "${mod_author}"

[[dependencies.dergstuff]]
modId="forge"
mandatory = true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.dergstuff]]
modId = "minecraft"
mandatory = true
versionRange = "${mc}"
ordering = "NONE"
side = "BOTH"